### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by YoushaExT** [tidalhq/ts-plugin-sort-import-suggestions#1]
I want to change the order of import for `SafeAreaView` like so:
```
import { SafeAreaView } from 'react-native-safe-area-context'
```
instead of:
```
import { SafeAreaView } from 'react-native'
```

<img width="768" alt="image" src="https://github.com/tidalhq/ts-plugin-sort-import-suggestions/assets/66265032/fc3a20f3-0041-42f9-9a89-4b28498fad8c">

I have added this line in `tsconfig` but it does not seem to work:

```
"plugins": [
      {
        "name": "ts-plugin-sort-import-suggestions",
        // Matches `@/`, `../` and `./`, move them up in the suggestions (This is the default config if you leave it empty)
        "moveUpPatterns": ["react-native-safe-area-context", "@/", "\\.{1,2}/"],
        // Move `dist` down in the suggestions, by deafult it's `[]`
        "moveDownPatterns": ["dist"]
      }
    ]
```

After making this change I ran 'Typescript: Restart TS Server' in VSCode command palette.

How can I make it work? and is it possible to see the logs inside `node_modules/ts-plugin-sort-import-suggestions/index.js`

**Comment by houkanshan** [comment]
Hi @YoushaExT , apologies for not catching your issue earlier.

Have you configured the VSCode to use the TypeScript from node_modules? By pressing Shift+Cmd+P and typing `Select TypeScript Version`

![image](https://github.com/tidalhq/ts-plugin-sort-import-suggestions/assets/657962/c9b2330f-d499-4756-8c57-7638790e32a2)

-----

To view the logs, please refer to the vscode dev doc: 
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#setting-up-typescript-server-logging

```
code -logToFile true -file ./log.txt -level verbose
```

**Comment by YoushaExT** [comment]
Thanks @houkanshan, It worked! The logs also worked, I was using `console.log` instead of `info.project.projectService.logger.info`.

Before:
![image](https://github.com/tidalhq/ts-plugin-sort-import-suggestions/assets/66265032/0f35655a-5220-4373-80f4-839e699c68fc)

After:
![image](https://github.com/tidalhq/ts-plugin-sort-import-suggestions/assets/66265032/4945d098-e8cd-4328-8685-3630da0c2f15)
