### ISSUE TITLE
Doesn't work in "💡Quick Fix" suggestions

### ISSUE THREAD

**Issue by movahhedi** [tidalhq/ts-plugin-sort-import-suggestions#5]
It doesn't work in "💡Quick Fix" suggestions.

![image](https://github.com/tidalhq/ts-plugin-sort-import-suggestions/assets/45717968/f6331f07-7274-4fa9-9840-708789c78aa0)

Although it's working in the import suggestions.
![image](https://github.com/tidalhq/ts-plugin-sort-import-suggestions/assets/45717968/172a937a-e4e2-49c0-b2e6-b7357306a4eb)

tsconfig.json
```json
//...
		"plugins": [
			{
				"name": "ts-plugin-sort-import-suggestions",
				"moveUpPatterns": ["#/", "@/", "\\.{1,2}/"],
				"moveDownPatterns": ["dist"]
			}
		]
//...
```

And yes, TypeScript is set to use the Workspace version.

**Comment by houkanshan** [comment]
Hi @movahhedi , this plugin only reorders the suggestions; it doesn't change how the TypeScript language server fixes problems, so the first screenshot is expected.

Were you expecting `../../../Basics/Language` to be `#Basics`? If so, maybe you can try to change the `typescript.preferences.importModuleSpecifier` setting in your VSCode configuration to either `non-relative` or `shortest`.

**Comment by movahhedi** [comment]
Setting it to `shortest` does work.
Bu can't we do the same we did with suggestions, to the Quick Fix suggestions? Is there a limitation?

**Comment by houkanshan** [comment]
I think it's depends on whether if the suggestions of path & the quick fix are from the same provider.

If these suggestions are all come from TS language server, I think you can ask in the [typescript repo](https://github.com/microsoft/TypeScript)

Closing it as it's not an issue of this plugin
